apiVersion: v1
kind: ConfigMap
metadata:
  name: bff-config
  namespace: paytogether
  labels:
    app: bff
data:
  # Fichier application.yml monté dans le conteneur sous /config/application.yml
  application.yml: |
    spring:
      profiles:
        active: prod
    # Propriétés métier/techniques non sensibles
    app:
      backend-url: http://bfb.prod.svc.cluster.local
      nomApplication: bff-paytogether

