apiVersion: v1
kind: ConfigMap
metadata:
  name: bff-config
  namespace: paytogether
  labels:
    app: bff
data:
  # Fichier application.properties monté dans le conteneur sous /config/application.properties
  application.properties: |
    # Profil actif
    spring.profiles.active=prod
    
    # Propriétés métier/techniques non sensibles
    spring.app.backend-url=http://bfb.prod.svc.cluster.local
    spring.application.name=bff-paytogether
