apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bff-ingress
  namespace: paytogether
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
#    nginx.ingress.kubernetes.io/rewrite-target: /$1
#    nginx.ingress.kubernetes.io/use-regex: "true"

spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - devbff.dealtogether.ca
      secretName: bff-tls
  rules:
  - host: devbff.dealtogether.ca
    http:
      paths:
      - path: /
      #pathType: ImplementationSpecific
        pathType: Prefix
        backend:
           service:
              name: bffprod-service
              port:
                number: 8193

