apiVersion: v1
kind: Secret
metadata:
  name: bff-secret
  namespace: paytogether
type: Opaque
stringData:
  # Exemple : variables sensibles encodées en base64 par Kubernetes lors de la création
  SPRING_DATASOURCE_PASSWORD: "superSecretPassword"
  API_KEY_EXTERNE: "cle-api-externe-xxxxx"

