apiVersion: v1
kind: Secret
metadata:
  name: bff-secret
  namespace: paytogether
type: Opaque
stringData:
  # MinIO Credentials
  minio.access.key: "ulrichAfric"
  minio.secret.key: "ulrSms@Afric"

  # Base de donn√©es
  SPRING_DATASOURCE_PASSWORD: "ZhKdrpgibRkzWodAw6rRABraPdXRcbpW"

  # JWT
  JWT_SECRET: "monSecretSuperSecurisePourPayTogether2024!"

  # API Auth
  API_KEY_EXTERNE: "votre-cle-api-auth"
