apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: paytogether
  labels:
    app: minio
spec:
  # Type ClusterIP : pour un MinIO qui tourne DANS le cluster Kubernetes
  type: ClusterIP
  selector:
    app: minio
  ports:
    - name: api
      protocol: TCP
      port: 9005
      targetPort: 9000
    - name: console
      protocol: TCP
      port: 9001
      targetPort: 9001

