apiVersion: v1
kind: Service
metadata:
  name: bffprod-service
  namespace: paytogether
  labels:
    app: bff
spec:
  type: ClusterIP
  selector:
    app: bff
  ports:
    - protocol: TCP
      port: 8193
      targetPort: 8080
